#!/bin/bash

if [ -d /var/lib/tftpboot ]; then
   for f in localboot kernel-x memtest86; do
      if [ ! -f /var/lib/tftpboot/$f ]; then
         cp -p /usr/share/netbootmgr/$f /var/lib/tftpboot
      fi
   done
   MEMTEST_BIN=$(MEMTEST=( /boot/memtest* ); echo ${MEMTEST[0]})
   if test "$MEMTEST_BIN" != "/boot/memtest*"
   then
      ln -sf $MEMTEST_BIN /var/lib/tftpboot/memtest86+
   fi
fi

exit 0
